[package]
name = "chronofold"
version = "0.1.0"
authors = ["Dominik Kellner <dkellner@dkellner.de>"]
edition = "2018"
description = "A replicated data structure for versioned text"
readme = "README.md"

[dependencies]
thiserror = "1.0.15"

[dev-dependencies]
anyhow = "1.0.28"
rand = "0.7.3"
proptest = "0.9.6"
