[package]
name = "chronofold"
version = "0.1.0"
authors = ["Dominik Kellner <dkellner@dkellner.de>"]
edition = "2018"
description = "A replicated data structure for versioned text"
readme = "README.md"

[dependencies]
